apiVersion: v1
kind: Service
metadata:
  name: my-portfolio-service
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "portfolio-backend-config"}'
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-portfolio-app
  type: LoadBalancer
